# Generated by Django 6.0.1 on 2026-02-10 15:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('course_code', models.CharField(help_text='강의 코드(예: CS101, ENG-202 등)', max_length=50)),
                ('is_public', models.BooleanField(default=False, help_text='공개 강의 여부 (예: 카탈로그에 노출할지 여부)')),
                ('account', models.ForeignKey(help_text='이 강의가 속한 계정(또는 하위 계정)', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.account')),
                ('term', models.ForeignKey(help_text='이 강의가 열리는 학기', on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='core.term')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('ta', 'TA'), ('observer', 'Observer'), ('designer', 'Designer')], help_text='이 섹션에서의 역할 (Student, Teacher 등)', max_length=20)),
                ('enrollment_state', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('concluded', 'Concluded'), ('pending', 'Pending')], default='pending', help_text='등록 상태', max_length=20)),
                ('grades', models.DecimalField(blank=True, decimal_places=2, help_text='현재 점수/성적 (선택 사항, 예: 95.50, 3.70 등)', max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='이 등록 레코드의 사용자', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollments',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='모듈 이름 (예: Week 1, Introduction 등)', max_length=255)),
                ('position', models.PositiveIntegerField(default=0, help_text='코스 내 모듈 순서')),
                ('unlock_at', models.DateTimeField(blank=True, help_text='이 날짜/시간 이후에 모듈이 열림', null=True)),
                ('require_sequential_progress', models.BooleanField(default=False, help_text='학생이 이 모듈의 아이템을 순서대로만 진행해야 하는지 여부')),
                ('course', models.ForeignKey(help_text='이 모듈이 속한 강의', on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course')),
                ('prerequisites', models.ManyToManyField(blank=True, help_text='이 모듈이 열리기 전에 완료되어야 하는 선행 모듈들', related_name='dependent_modules', to='courses.module')),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'ordering': ['course', 'position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ModuleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0, help_text='모듈 내 아이템 순서')),
                ('indent', models.PositiveSmallIntegerField(default=0, help_text='모듈 내 들여쓰기 레벨 (0~5)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('object_id', models.PositiveIntegerField(help_text='연결된 객체의 PK')),
                ('completion_requirement', models.CharField(blank=True, choices=[('must_view', 'Must view'), ('must_submit', 'Must submit'), ('min_score', 'Minimum score')], help_text='이 아이템의 완료 조건 (must_view, must_submit, min_score 등)', max_length=20, null=True)),
                ('content_type', models.ForeignKey(help_text='연결된 객체 타입 (Page, Assignment 등)', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('module', models.ForeignKey(help_text='이 아이템이 속한 모듈', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='courses.module')),
            ],
            options={
                'verbose_name': 'Module item',
                'verbose_name_plural': 'Module items',
                'ordering': ['module', 'position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='분반 이름(예: 001반, A반 등)', max_length=255)),
                ('course', models.ForeignKey(help_text='이 분반이 속한 강의', on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='courses.course')),
                ('students', models.ManyToManyField(blank=True, help_text='이 분반에 수강 등록된 학생들', related_name='enrolled_sections', through='courses.Enrollment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
            },
        ),
        migrations.AddField(
            model_name='enrollment',
            name='section',
            field=models.ForeignKey(help_text='사용자가 등록된 분반', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.section'),
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(help_text='HTML 형태로 저장되는 페이지 본문')),
                ('is_published', models.BooleanField(default=False, help_text='학생에게 공개 여부')),
                ('is_front_page', models.BooleanField(default=False, help_text='코스 홈(Front Page)로 사용할지 여부')),
                ('course', models.ForeignKey(help_text='이 페이지가 속한 강의', on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='courses.course')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_front_page', True)), fields=('course',), name='unique_front_page_per_course')],
            },
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('user', 'section'), name='unique_user_section_enrollment'),
        ),
    ]
