# Generated by Django 6.0.1 on 2026-02-10 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='과제 설명 (리치 텍스트 / HTML 등)')),
                ('points_possible', models.DecimalField(decimal_places=2, help_text='배점 (소수점 둘째 자리까지, 예: 100.00, 10.50)', max_digits=5)),
                ('due_at', models.DateTimeField(blank=True, help_text='마감일', null=True)),
                ('unlock_at', models.DateTimeField(blank=True, help_text='과제를 열어두는 시작 시각', null=True)),
                ('lock_at', models.DateTimeField(blank=True, help_text='과제가 완전히 닫히는 시각', null=True)),
                ('submission_types', models.JSONField(blank=True, default=list, help_text="허용되는 제출 유형 리스트. 예: ['online_text_entry', 'online_upload', 'online_url', 'media_recording', 'none']")),
                ('grading_type', models.CharField(choices=[('pass_fail', 'Pass / Fail'), ('percent', 'Percent'), ('letter_grade', 'Letter grade'), ('points', 'Points')], default='points', help_text='채점 방식 (pass_fail, percent, letter_grade, points)', max_length=20)),
                ('published', models.BooleanField(default=False, help_text='학생에게 과제가 공개되었는지 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(help_text='이 과제가 속한 강의', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.course')),
            ],
            options={
                'verbose_name': 'Assignment',
                'verbose_name_plural': 'Assignments',
                'ordering': ['course', 'due_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt', models.PositiveIntegerField(default=1, help_text='제출 시도 횟수 (1부터 시작)')),
                ('body', models.TextField(blank=True, help_text='온라인 텍스트 입력 내용', null=True)),
                ('url', models.URLField(blank=True, help_text='온라인 URL 제출 (예: Git 리포지토리, 외부 페이지 링크)', null=True)),
                ('attachment', models.FileField(blank=True, help_text='파일 업로드 제출', null=True, upload_to='submissions/')),
                ('score', models.DecimalField(blank=True, decimal_places=2, help_text='획득 점수', max_digits=5, null=True)),
                ('grade', models.CharField(blank=True, help_text='등급 표기 (예: A, B+, 95%)', max_length=50, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, help_text='실제 제출 시각', null=True)),
                ('workflow_state', models.CharField(choices=[('submitted', 'Submitted'), ('graded', 'Graded'), ('unsubmitted', 'Unsubmitted'), ('late', 'Late'), ('missing', 'Missing')], default='unsubmitted', help_text='제출 상태 (submitted, graded, unsubmitted, late, missing)', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(help_text='제출 대상 과제', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='courses.assignment')),
                ('user', models.ForeignKey(help_text='제출한 사용자', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Submission',
                'verbose_name_plural': 'Submissions',
                'ordering': ['assignment', 'user', 'attempt'],
                'constraints': [models.UniqueConstraint(fields=('assignment', 'user', 'attempt'), name='unique_assignment_user_attempt')],
            },
        ),
    ]
