# Generated by Django 6.0.1 on 2026-02-10 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_assignment_submission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='문제 내용 (HTML 가능)')),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple choice'), ('true_false', 'True / False'), ('short_answer', 'Short answer'), ('essay', 'Essay')], default='multiple_choice', help_text='문제 유형', max_length=20)),
                ('points', models.DecimalField(decimal_places=2, default=1, help_text='이 문항의 배점', max_digits=5)),
                ('position', models.PositiveIntegerField(default=0, help_text='퀴즈 내 문항 순서')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['quiz', 'position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='보기 내용', max_length=255)),
                ('is_correct', models.BooleanField(default=False, help_text='정답 여부')),
                ('question', models.ForeignKey(help_text='이 보기가 속한 문항', on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='courses.question')),
            ],
            options={
                'verbose_name': 'Choice',
                'verbose_name_plural': 'Choices',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_limit_minutes', models.PositiveIntegerField(blank=True, help_text='제한 시간(분 단위). 비워두면 시간 제한 없음', null=True)),
                ('allowed_attempts', models.IntegerField(default=-1, help_text='허용 시도 횟수. -1은 무제한')),
                ('shuffle_answers', models.BooleanField(default=False, help_text='문항의 보기를 섞을지 여부')),
                ('quiz_type', models.CharField(choices=[('graded_quiz', 'Graded quiz'), ('practice_quiz', 'Practice quiz'), ('graded_survey', 'Graded survey'), ('ungraded_survey', 'Ungraded survey')], default='graded_quiz', help_text='퀴즈 유형 (graded_quiz, practice_quiz 등)', max_length=20)),
                ('assignment', models.OneToOneField(help_text='이 퀴즈가 연결된 과제', on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='courses.assignment')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(help_text='이 문항이 속한 퀴즈', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.quiz'),
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(blank=True, help_text='퀴즈를 시작한 시각', null=True)),
                ('finished_at', models.DateTimeField(blank=True, help_text='퀴즈를 완료한 시각', null=True)),
                ('submission', models.OneToOneField(help_text='이 퀴즈 시도에 대응하는 과제 제출', on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempt', to='courses.submission')),
            ],
            options={
                'verbose_name': 'Quiz attempt',
                'verbose_name_plural': 'Quiz attempts',
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_response', models.TextField(blank=True, help_text='주관식/서술형 답변 내용', null=True)),
                ('attempt', models.ForeignKey(help_text='이 답안이 속한 퀴즈 시도', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='courses.quizattempt')),
                ('question', models.ForeignKey(help_text='답을 작성한 문항', on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='courses.question')),
                ('selected_choice', models.ForeignKey(blank=True, help_text='객관식 선택지 (해당되는 경우에만)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_answers', to='courses.choice')),
            ],
            options={
                'verbose_name': 'Student answer',
                'verbose_name_plural': 'Student answers',
                'ordering': ['attempt', 'question_id'],
            },
        ),
    ]
