# Generated by Django 6.0.2 on 2026-02-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_question_choice_quiz_question_quiz_quizattempt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='feedback',
            field=models.TextField(blank=True, help_text='Instructor feedback for this submission', null=True),
        ),
    ]
